SforAiDl/KD_Lib

.gitignore, CONTRIBUTING.rst, CONTRIBUTORS.rst, KD_Lib/TAKD/data_loader.py, KD_Lib/TAKD/main.py, KD_Lib/TAKD/training.py, KD_Lib/TAKD/utils.py, KD_Lib/models/resnet.py, tests/test_KD_Lib.py
- Resolves issue #6 
- few minor edits in ```CONTRIBUTING.rst```
=> Implements TAKD

KD_Lib/RKD/__init__.py, KD_Lib/RKD/loss_metric.py, KD_Lib/original/mnist.py, KD_Lib/original/train.py, tests/test_KD_Lib.py
Passes ```epochs=1``` tests on local machine, so changed to ```epochs=0``` to prevent CI Tests from hanging.
Addresses issue #12
=> Relational Knowledge Distillation

README.rst
=> Minor readme fixes

KD_Lib/__init__.py, KD_Lib/common/__init__.py, KD_Lib/common/base_class.py, KD_Lib/original/__init__.py, KD_Lib/original/original_paper.py, requirements_dev.txt, tests/test_KD_Lib.py
Now that we have a good amount of implementations. We can start giving a shape to this library. Let me know of your thoughts on this direction @NeelayS @khizirsiddiqui @avishreekh
=> Add BaseClass

KD_Lib/__init__.py, KD_Lib/attention/__init__.py, KD_Lib/attention/attention.py, KD_Lib/common/base_class.py, tests/test_KD_Lib.py
=> Add Attention

KD_Lib/noisy/__init__.py, KD_Lib/noisy/noisy.py, KD_Lib/noisy/utils.py, tests/test_KD_Lib.py
=> Refactor NoisyTeacher

KD_Lib/TAKD/takd.py, KD_Lib/attention/attention.py, KD_Lib/common/base_class.py, KD_Lib/noisy/noisy.py, KD_Lib/original/original_paper.py, requirements_dev.txt, tests/test_KD_Lib.py
=> Add Tensorboard

KD_Lib/RKD/loss_metric.py, KD_Lib/TAKD/takd.py, KD_Lib/attention/attention.py, KD_Lib/attention/loss_metric.py, KD_Lib/common/base_class.py, KD_Lib/models/lenet.py, KD_Lib/models/nin.py, KD_Lib/models/resnet.py, KD_Lib/models/shallow.py, KD_Lib/noisy/noisy.py, KD_Lib/original/original_paper.py
=> Document Base class init

KD_Lib/common/base_class.py
=> Save device errors!

KD_Lib/__init__.py, KD_Lib/models/__init__.py, KD_Lib/models/lstm.py, tests/test_KD_Lib.py
A basic LSTM module for classification. It should be helpful with NLP tasks.
=> Add LSTMNet

KD_Lib/models/shallow.py, KD_Lib/teacher_free/__init__.py, KD_Lib/teacher_free/self_training.py, KD_Lib/teacher_free/virtual_teacher.py, tests/test_KD_Lib.py
=> Teacher Free implementation

KD_Lib/BANN/BANN.py, KD_Lib/BANN/__init__.py, KD_Lib/common/base_class.py, README.rst, docs/conf.py, setup.py, tests/test_KD_Lib.py
Issue #42 
- Add BANN Module
- Add tests for BANN
I have also moved the main implementation in `BaseClass::train_student()` to a new function `BaseClass::_train_student()` and `BaseClass::evaluate` to ``BaseClass::_evaluate_model()`. `BANN` trains several generation of models to create an ensemble. This structure allows more flexibility around the `evaluate` and `train_student` methods.
Remaining
- Documentation
=> Born Again Neural Networks

KD_Lib/noisy/__init__.py, KD_Lib/noisy/messy_collab.py, KD_Lib/noisy/noisy_teacher.py, KD_Lib/noisy/soft_random.py, README.rst, tests/test_KD_Lib.py
These techniques target improving model robustness and generalization. If/when the directory structure of the library is modified, maybe we can group implementations according to the purpose they serve.  
Issue #47
=> Implements Soft Randomization and Messy Collaboration

KD_Lib/KD/vision/attention/attention.py
=> Fix Attention Loss Calculation

KD_Lib/KD/common/base_class.py, KD_Lib/KD/vision/KA/LSR.py
- Moves losses in teacher training and in arguments to device.
- Fixes error when saving models to non-existing custom paths.
- A minor typo in LSR loss :p
=> Multiple Minor FIxes

KD_Lib/KD/vision/TAKD/takd.py
- move loss fn in TAKD to device
- fix logging of loss in train_distill_model (#92 )
=> Fix TAKD Logging and Move Loss Function to Device

KD_Lib/KD/vision/mean_teacher/mean_teacher.py
=> Fix Mean Teacher

setup.py
=> Fix setup.py not installing modules

.github/workflows/python-package.yml
Solves #108
@Het-Shah you will need to add `PYPI_USERNAME` and `PYPI_PASSWORD` to the github secrets and this should work fine
=> Add pypi packaging using GitHub Actions

KD_Lib/KD/common/base_class.py, KD_Lib/KD/text/BERT2LSTM/bert2lstm.py, KD_Lib/KD/vision/BANN/BANN.py, KD_Lib/KD/vision/CSKD/cskd.py, KD_Lib/KD/vision/DML/dml.py, KD_Lib/KD/vision/RCO/rco.py, KD_Lib/KD/vision/TAKD/takd.py, KD_Lib/KD/vision/noisy/messy_collab.py, KD_Lib/KD/vision/noisy/soft_random.py, KD_Lib/KD/vision/teacher_free/self_training.py, KD_Lib/KD/vision/teacher_free/virtual_teacher.py
Added validation on the fly (#95):
1. Ensured that an evaluate method is present in KD algorithms which is called while training
2. Best model is saved based on validation performance
Some questions (and potential problems)
1. Did not add the enhancement to DML and TAKD as that would require substantial changes to their evaluate methods. Please let me know if these can be changed.
2. Evaluation methods seem to be returning the accuracy in most cases (should we also not be returning the model outputs if the evaluate method is used independently?). The `_evaluate_model` method returns outputs also but this is ignored in the `evaluate` method, is there a reason for doing so?
Please let me know if the current changes need any additional modifications.
Thanks!
=> Add validation on the fly

KD_Lib/KD/common/base_class.py, KD_Lib/KD/vision/DML/dml.py, setup.py, tests/test_KD_Lib.py
=> Fixes issue in DML

KD_Lib/KD/vision/DML/dml.py, KD_Lib/Pruning/__init__.py, KD_Lib/Pruning/common/__init__.py, KD_Lib/Pruning/common/iterative_base_class.py, KD_Lib/Pruning/lottery_tickets/__init__.py, KD_Lib/Pruning/lottery_tickets/lottery_tickets.py, KD_Lib/Pruning/weight_threshold/__init__.py, KD_Lib/Pruning/weight_threshold/weight_threshold_pruning.py, tests/test_KD_Lib.py
This work aims to do the following:
1. Create a `BaseIterativePruner` which can serve as the base class for all iterative pruning implementations.
2. Any new pruning technique can be added by extending the `BaseIterativePruner` class and implementing the `prune_model` method. The `prune_model` method should zero the parameters of the model that need to be pruned.
3. Re-implement Lottery Tickets Pruning by extending the new base class.
4. Add a new pruning method: Weight Threshold Pruning that prunes all weights in the model whose magnitudes are lesser than a given threshold.
=> Modularized pruning and the addition of Weight Threshold Pruning method
